### ISSUE TITLE
Issue with downloading anime

### ISSUE THREAD

**Issue by MidnightKittenCat** [h4rldev/animdl-tui#1]
Usage: animdl [OPTIONS] COMMAND [ARGS]...
Try 'animdl --help' for help.

Error: No such command 'download-s'.

 Press any key to continue

**Comment by h4rldev** [comment]
I haven't pushed to this in a while, I'll see what I can do.

-------- Original Message --------

**Comment by MidnightKittenCat** [comment]
Anything so far?

**Comment by h4rldev** [comment]
Going to rework the code, shorten it and fix it because it's not been updated since animix died

**Comment by MidnightKittenCat** [comment]
Traceback (most recent call last):
  File "C:\Users\USER\animdl-tui\main.py", line 10, in <module>
    from modules.checks import doespackageexist, ismoduleon, checkifexists, checkiffalse
  File "C:\Users\USER\animdl-tui\modules\checks.py", line 5, in <module>
    from colors import cyan, red, reset
ModuleNotFoundError: No module named 'colors'

Not sure what I'm doing wrong.

**Comment by MidnightKittenCat** [comment]
as

**Comment by h4rldev** [comment]
It's not done yet, currently doing a rework

**Comment by h4rldev** [comment]
It's currently not functional
